apiVersion: apps/v1
kind: Deployment
metadata:
  name: Kubernetes-Kafka-Connect-Operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: Kubernetes-Kafka-Connect-Operator
  template:
    metadata:
      labels:
        name: Kubernetes-Kafka-Connect-Operator
    spec:
      serviceAccountName: Kubernetes-Kafka-Connect-Operator
      containers:
        - name: Kubernetes-Kafka-Connect-Operator
          # Replace this with the built image name
          image: docker.io/kafkaconnect/k8s-operator:0.0.2
          command:
          - Kubernetes-Kafka-Connect-Operator
          imagePullPolicy: Always
          ports:
          - containerPort: 6443
            name: https
          - containerPort: 8080
            name: http
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "Kubernetes-Kafka-Connect-Operator"

---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta2.custom.metrics.k8s.io
spec:
  service:
    name: Kubernetes-Kafka-Connect-Operator-svc
    namespace: default
  group: custom.metrics.k8s.io
  version: v1beta2
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 200

---
apiVersion: v1
kind: Service
metadata:
  name: Kubernetes-Kafka-Connect-Operator-svc
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  - name: http
    port: 80
    targetPort: 8080
  selector:
    name: Kubernetes-Kafka-Connect-Operator